work_directory="work"

# This file
alias ali="nano ~/.zshrc"
alias cpali="(cd ~ && cp .zshrc zshrc_copy && echo aliases copied!)"

# Git
alias ga="git add ."
alias gb="git branch"
alias gf="git fetch --update-head-ok"
alias gs="git status"
alias grfl="git reflog"
alias gp="git push"
alias gpl="git pull --no-ff"
alias gl="git log"
alias gcl="git clean -df *"
alias grt="git restore ."
alias gpf="git push --force"
alias gsw="git switch"
alias grslc="git reset --soft HEAD^" #grslc = git reset soft last commit
alias grhlc="git reset --hard HEAD^" #grhlc = git reset hard last commit
alias gd="git diff HEAD"
alias gauto="ga && git commit -m 'autosave'"
alias gas="gauto && git checkout"
alias gca="git gc --aggressive"
alias gcd="git commit --no-edit"
alias gcne="ga && gcd && gp"

gm() {
main_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
git fetch origin $main_branch:$main_branch -u && git merge $main_branch --no-edit
}

main() {
main_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
gch $main_branch
}

gnb() {
if [ -z "$1" ]
then
echo "Provide a new branch name"
return 0
fi
main && gnbs $1 && gm && gs
}

gnbs() {
git pull && git checkout -b $1 && git status
}

gba() {
if [ -z "$1" ]
then
git branch -a
else
cd ~/$work_directory/$1 && git branch -a
fi
}

grs() {
if [ -z "$1" ]
then
git reset --soft HEAD^
else
git reset --soft HEAD~$1
fi
}

gr() {
if [ -z "$1" ]
then
git restore --staged . && git restore . && git clean -df .
else
git restore --staged $1 && git restore $1 && git clean -df $1
fi
}

gfm() {
main_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
git fetch origin $main_branch:$main_branch
}

gch() {
if [ -z "$1" ]
then
echo "Provide a new branch name"
return 0
fi
git checkout $1 2>/dev/null
if [ $? -ne 0 ]; then
  echo "Branch '$1' does not exist."
  matching_branches=$(gba | grep $1)
  if [ -z "$matching_branches" ]; then
    echo "And there are no matching branches. So sorry mate."
  else
    echo "Here are some branches matching:"
    echo "$matching_branches"
  fi
fi
}

# Yarn
alias yu="yarn upgrade --frozen-lockfile"

yr() {
if [ -z "$1" ]
then
rm -rf node_modules && sudo rm yarn.lock && yarn
else
(cds $1 && rm -rf node_modules && sudo rm yarn.lock && yarn)
fi
}

yrf() {
if [ -z "$1" ]
then
rm -rf node_modules && sudo rm yarn.lock && sudo rm -rf dist && yarn
else
(cds $1 && rm -rf node_modules && sudo rm yarn.lock && sudo rm -rf dist && yarn)
fi
}

# Filesystem
alias l="ls -la"
alias hm="cd ~"
alias rmd="sudo rm -rf"

cds() {
if [ -z "$1" ]
then
cd ~/$work_directory
else
cd ~/$work_directory/$1 && gs
fi
}

# Terminal
his() {
history | grep $1
}

# K8s
alias k="kubectl"
alias kx="kubectx"
alias kds="kubectl describe pod"
alias ke="kubectl edit pod"
alias kp="kubectl get pod --label-columns mode --sort-by=.metadata.name"
alias pod="kp"
alias opd="pod"
alias pdo="pod"

kd() {
for arg in "$@"; do
  kubectl delete pod -l app="$arg"
done
}

kdf() {
k delete pod $1 --grace-period=0 --force
}

kl() {
kubectl logs -f -l app=$1
}